#%RAML 0.8
title: Order System
mediaType: application/json
/products:
  get:
    description: As a user, I'd like to see all the products online so that I can choose different products.
    responses:
      200:
        body:
          application/json:
            example: !include example/products.json
  /{product_id}:
    get:
      description: As a user, I'd like to see one of the products because I would like to know more detail of this product.
      responses:
        200:
          body:
            application/json:
              example: !include example/product.json
    /current_price:
      get:
        description: As a user, I'd like to know the current price of this product so that I can decide if it is too expensive.
        responses:
          200:
            body:
              application/json:
                example: !include example/current_price.json